### ISSUE TITLE
Merging conflict 

### ISSUE THREAD

**Issue by nguyenpham207** [sei-ec-remote/project-4-issues#208]
### What's the problem you're trying to solve?
 I have a merging problem with my teammate again. 

### Post any code you think might be relevant (one fenced block per file)
```
git rebase --continute
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
```
From https://github.com/Salam3377/React-Lux-house
 * branch            main       -> FETCH_HEAD
fatal: Not possible to fast-forward, aborting.
```

### What is your best guess as to the source of the problem?

2 working trees 
### What things have you already tried to solve the problem?
followed the last issue.

**Paste a link to your repository here**

**Comment by kestler01** [comment]
work with your teammate to review the merge together, determine which lines of conflicting code to keep and not break the project. We expect you to be able to navigate these together since we all worked on teams in P3 and the instructional team isn't going to know the ins and outs of your individual projects.
