### ISSUE TITLE
Many to Many

### ISSUE THREAD

**Issue by spenserg92** [sei-ec-remote/project-4-issues#298]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
How to associate my platforms with my games

### Post any code you think might be relevant (one fenced block per file)
```
```

### What is your best guess as to the source of the problem?
I'm not sure. Could use some direction on where to start

### What things have you already tried to solve the problem?

**Paste a link to your repository here**
https://github.com/spenserg92/Client-GameHub
https://github.com/spenserg92/GameHub

**Comment by nayaba** [comment]
I would imagine a platform could have many games in the same way that a pet could have many toys (which is why we used an array of toys in our pet model during the codealong).  MongoDB doesn't have the same limitations as PSQL, which means you can be much more flexible with your relationships.  I can't see your ERDs on your repo though - could you post them here?

**Comment by spenserg92** [comment]
![ERD](https://github.com/sei-ec-remote/project-4-issues/assets/149332042/74333260-b89a-4ec2-a4ea-871660d1594d)

**Comment by nayaba** [comment]
I'm assuming Game Console was replaced by Platform when you actually starting coding...

I would revise the Platform model slightly to more closely align with the [Pet model](https://github.com/timmshinbone/applePiePetsAPI/blob/main/app/models/pet.js) we used in class.

Specifically I believe it would be beneficial to modify the games attribute to be an array that references the gameSchema, just like in class we created a toys array that references the toySchema.

**Comment by spenserg92** [comment]
Yes I replaced console with platform. Thanks for the help!
